### ISSUE TITLE
Add ZorroVPN as VPN provider 

### ISSUE THREAD

**Issue by hallmichael868** [haugene/vpn-configs-contrib#4]
Which provider?
zorrovpn.com

Where are the configs?
https://ufile.io/28l98gm8

**Comment by haugene** [comment]
Your link has timed out @hallmichael868, upload it again?

**Comment by hallmichael868** [comment]
@haugene sure: https://we.tl/t-pjmSUWYesM

**Comment by haugene** [comment]
The configs refer to a .pem file that is not part of the zip:
```
tls-auth zorro-ta.pem 1
ca zorro-ca.pem
cert zorro-user.pem
key zorro-user.pem
```

I need that as well.

**Comment by hallmichael868** [comment]
As far as I understand this (and that might not be far) those files are different for each user and hold their individual keys. I don't think it would be a good idea to share those.

**Comment by haugene** [comment]
Yeah. Some providers do it like that, not using a username/password but rather a private key. But if we can't add the configs for the provider because they are sensitive, well... Then we can't add the configs for the provider.

Closing this and you should have a look at https://haugene.github.io/docker-transmission-openvpn/supported-providers/#using_a_custom_provider

I'm in a process of rewriting the documentation and that part could need a brush up, but all you need to do is just to put the configs in a folder on your host and mount them to the container. Then you can use your own configs without it being added anywhere else.
